
- name: Ensure mount folders exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /mnt/motion
    - /mnt/shared
  become: true

- name: Mount Ext USB HDD 500 GB to /mnt/motion
  ansible.posix.mount:
    path: /mnt/motion
    src: UUID=f534bea8-7af7-4f71-8cd8-5f1103ace7c5
    fstype: ext4
    opts: defaults
    state: mounted
  become: true

- name: Mount Ext USB HDD 500 GB to /mnt/shared
  ansible.posix.mount:
    path: /mnt/shared
    src: UUID=a4834d8b-70a8-4e74-bbce-2484c824d94a
    fstype: ext4
    opts: defaults
    state: mounted
  become: true

- name: Remove docker
  apt:
    name: docker-ce
    state: absent
  become: true

- name: Remove docker-ce-cli
  apt:
    name: docker-ce-cli
    state: absent
  become: true

- name: Install docker from get.docker.com
  shell: curl -fsSL https://get.docker.com | bash
  become: true

- name: Create docker network
  shell: docker network create public_network
  become: true

- name: remove default netplan config *.yaml
  file:
    path: /etc/netplan/*.yaml
    state: absent
  become: true

- name: Configure static IP using netplan
  copy:
    dest: /etc/netplan/01-static.yaml
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          eth0:
            dhcp4: false
            addresses:
              - 192.168.0.35/24      
            gateway4: 192.168.0.1      
            nameservers:
              addresses:
                - 192.168.0.1
                - 8.8.8.8
                - 1.1.1.1

- name: Apply netplan
  command: netplan apply
  become: true
