- name: Install needed packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nfs-kernel-server
  become: true

- name: Mount Ext Usb HDD 500 GB ext4 for /mnt/motion for MOTION NVR
  ansible.posix.mount:
    path: /mnt/motion
    src: UUID=f534bea8-7af7-4f71-8cd8-5f1103ace7c5
    fstype: ext4
    opts: defaults
    state: mounted
  become: true

- name: Mount Ext Usb HDD 640GB ext4 Network Share
  ansible.posix.mount:
    path: /mnt/shared
    src: UUID=083403ad-e6db-43fd-a2fc-0bf50640ed0e
    fstype: ext4
    opts: defaults
    state: mounted
  become: true

- name: Configure NFS exports  
  lineinfile:
    path: /etc/exports
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
    regexp: "^{{ item.line }}$"
  loop:
    - { line: "/mnt/shared *(rw,sync,no_root_squash,no_subtree_check)" }
    - { line: "/mnt/motion *(rw,sync,no_root_squash,no_subtree_check)" }    
  become: true

- name: restart nfs server  
  service:
    name: nfs-server
    state: restarted
  become: true
  