version: '3.8'

services:
  miniserve:
    image: svenstaro/miniserve
    # ["/srv", "--upload-files"]
    command: ["/srv"]
    volumes:
      - /mnt/shared:/srv/shared
      - /mnt/motion:/srv/motion    
    ports:
      - target: 8080
        published: 8080
        mode: host        
