version: "3.7"

services:
  agent:
    image: portainer/agent:2.27.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host  # Add this line to mount the host root
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.27.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify  # Use Portainer Agent for communication
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 9000
        published: 9000
        mode: host

volumes:
  portainer_data:
    external: true
    name: portainer_data
