version: '3.8'

services:
  postgresql:
    image: arm64v8/postgres:17
    environment:
      POSTGRES_USER: ainbidev
      POSTGRES_PASSWORD: 4!nb1deV
    volumes:
      - postgre_sql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network_public
    restart: always

volumes:
  postgre_sql:

networks:
  network_public:
    external: true