version: "3.7"

services:
  redis:
    image: arm64v8/redis:latest
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]
    volumes:
      - redis_data:/data
    networks:
      - network_public

volumes:
  redis_data:

networks:
  network_public:
    external: true