version: "3.7"

services:
  redis:
    image: arm64v8/redis:latest
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]
    volumes:
      - redis_data:/data
    networks:
      - network_public
    deploy:
      placement:
        constraints:
          - node.role == manager          
      resources:
        limits:
          cpus: "4"
          memory: 4096M

volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  network_public:
    external: true
    name: network_public