# ‼️ No “auth:” section – that switches Samba into guest-only mode.

global:
  - "map to guest = Bad User"
  - "guest account = nobody"
  - "server role = standalone server"
  - "log level = 1"

share:
  - name: homeschooling
    path: /samba/homeschooling
    browsable: yes
    readonly: no
    guestok: yes
    guestonly: yes          # synonym for ‘only guest’; blocks real users
    # Make everything appear as UID/GID 1000 on the host:
    extra:
      - "force user = 1000"
      - "force group = 1000"
      - "create mask = 0664"
      - "directory mask = 0775"
