global:
  - "server role = standalone server"
  - "map to guest = Bad User"
  - "guest account = nobody"
  - "host msdfs = no"          # hides the DFS hostname warning
  - "log level = 1"

share:
  - name: homeschooling
    path: /samba/homeschooling  # MUST match the mount
    browsable: yes
    readonly: no
    guestok: yes
    guestonly: yes
    recycle: yes
    extra:
      - "force user = 1000"
      - "force group = 1000"
      - "create mask = 0664"
      - "directory mask = 0775"
