- name: Configure and install careas_apps website
  hosts: server3
  become: true  # Elevates privileges for all tasks in this playbook
  become_user: root  # Specifies to run tasks as root
  roles:
    - site_careas
